# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Product3
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Getting Started
    output: web, pdf
    folderitems:
    - title: Product 3 home
      url: /p3_landing_page.html
      output: web

    - title: Sample 1
      url: /p3_sample1.html
      output: web, pdf


  - title: Another heading
    output: web, pdf

    folderitems:
    - title: Sample 3
      url: /p3_sample3.html
      output: web, pdf

